### ISSUE TITLE
Отсутствуют некоторые файлы в SDK

### ISSUE THREAD

**Issue by nevigen** [yandex-money/yandex-money-cms-v2-joomshopping#13]
В частности, lib\Common\AbstractPaymentRequest.php который необходим например в lib\Request\Payments\CreatePaymentRequest.php

Так же не срабатывает переход на оплату при завершении заказа, пишет

> Пожалуйста, введите правильный платежные данные

**Comment by ostulov** [comment]
Благодарю, обновим файлы в ближайшее время.

Для решения проблемы с переходом к оплате напишите нам письмо на почту cms@yamoney.ru с указанием Вашего shopid и подробностями проблемы.

**Comment by ostulov** [comment]
Обновление файлов SDK произведено.
