### ISSUE TITLE
Падение скрипта, генерирующего форму выбора доступных способов оплаты.

### ISSUE THREAD

**Issue by tnt4brain** [yandex-money/yandex-money-cms-v2-joomshopping#20]
Скрипт генерации формы содержит синтаксическую ошибку. 
Вот [PR с исправлением](https://github.com/yandex-money/yandex-money-cms-v2-joomshopping/pull/19).
Лог работы текущей, неисправленной версии:
>PHP Warning:  constant(): Couldn't find constant Укажите телефон in Joomla!root/components/com_jshopping/payments/pm_yandex_money/payment_form_kassa.php on line 86"
>PHP Stack trace:"
>PHP   1. {main}() Joomla!root/index.php:0"
>PHP   2. Joomla\CMS\Application\SiteApplication->execute() Joomla!root/index.php:49"
>PHP   3. Joomla\CMS\Application\SiteApplication->doExecute() Joomla!root/libraries/src/Application/CMSApplication.php:196"
>PHP   4. Joomla\CMS\Application\SiteApplication->dispatch() Joomla!root/libraries/src/Application/SiteApplication.php:233"
>PHP   5. Joomla\CMS\Component\ComponentHelper::renderComponent() Joomla!root/libraries/src/Application/SiteApplication.php:194"
>PHP   6. Joomla\CMS\Component\ComponentHelper::executeComponent() Joomla!root/libraries/src/Component/ComponentHelper.php:377"
>PHP   7. require_once() Joomla!root/libraries/src/Component/ComponentHelper.php:402"
>PHP   8. JshoppingControllerCheckout->execute() Joomla!root/components/com_jshopping/jshopping.php:25"
>PHP   9. JshoppingControllerCheckout->step3() Joomla!root/libraries/src/MVC/Controller/BaseController.php:710"
>PHP  10. jshopCheckoutPayment->getCheckoutListPayments() Joomla!root/components/com_jshopping/controllers/checkout.php:153"
>PHP  11. jshopPaymentMethod->loadPaymentForm() Joomla!root/components/com_jshopping/models/checkoutpayment.php:79"
>PHP  12. pm_yandex_money->showPaymentForm() Joomla!root/components/com_jshopping/tables/paymentmethod.php:206"
>PHP  13. include() Joomla!root/components/com_jshopping/payments/pm_yandex_money/pm_yandex_money.php:68"
>PHP  14. constant() Joomla!root/components/com_jshopping/payments/pm_yandex_money/payment_form_kassa.php:86"
>PHP Warning:  constant(): Couldn't find constant Укажите логин в Альфа-клике in Joomla!root/components/com_jshopping/payments/pm_yandex_money/payment_form_kassa.php on line 93"
>PHP Stack trace:"
>PHP   1. {main}() Joomla!root/index.php:0"
>PHP   2. Joomla\CMS\Application\SiteApplication->execute() Joomla!root/index.php:49"
>PHP   3. Joomla\CMS\Application\SiteApplication->doExecute() Joomla!root/libraries/src/Application/CMSApplication.php:196"
>PHP   4. Joomla\CMS\Application\SiteApplication->dispatch() Joomla!root/libraries/src/Application/SiteApplication.php:233"
>PHP   5. Joomla\CMS\Component\ComponentHelper::renderComponent() Joomla!root/libraries/src/Application/SiteApplication.php:194"
>PHP   6. Joomla\CMS\Component\ComponentHelper::executeComponent() Joomla!root/libraries/src/Component/ComponentHelper.php:377"
>PHP   7. require_once() Joomla!root/libraries/src/Component/ComponentHelper.php:402"
>PHP   8. JshoppingControllerCheckout->execute() Joomla!root/components/com_jshopping/jshopping.php:25"
>PHP   9. JshoppingControllerCheckout->step3() Joomla!root/libraries/src/MVC/Controller/BaseController.php:710"
>PHP  10. jshopCheckoutPayment->getCheckoutListPayments() Joomla!root/components/com_jshopping/controllers/checkout.php:153"
>PHP  11. jshopPaymentMethod->loadPaymentForm() Joomla!root/components/com_jshopping/models/checkoutpayment.php:79"
>PHP  12. pm_yandex_money->showPaymentForm() Joomla!root/components/com_jshopping/tables/paymentmethod.php:206"
>PHP  13. include() Joomla!root/components/com_jshopping/payments/pm_yandex_money/pm_yandex_money.php:68"
>PHP  14. constant() Joomla!root/components/com_jshopping/payments/pm_yandex_money/payment_form_kassa.php:93"

**Comment by ostulov** [comment]
Спасибо, проверим.

**Comment by ostulov** [comment]
Было исправлено в версии 1.1.3
