### ISSUE TITLE
ндс

### ISSUE THREAD

**Issue by logger55** [yandex-money/yandex-money-cms-v2-joomshopping#21]
ндс 18% осталось старое значение
https://github.com/yandex-money/yandex-money-cms-v2-joomshopping/blob/master/src/components/com_jshopping/payments/pm_yandex_money/3x/yandex_kassa.php

**Comment by ostulov** [comment]
Добрый день!

Мы планируем исправить название, которое показывается для данной ставки. По факту, с 1 января значение, которое ранее использовалось для ставки 18%, стало обозначать 20%.

**Comment by ostulov** [comment]
Исправлено в версии 1.1.5
