### ISSUE TITLE
Какая версия последняя 1.5.5 или 1.0.11 ?

### ISSUE THREAD

**Issue by korenevskiy** [yandex-money/yandex-money-cms-v2-joomshopping#7]
На странице https://money.yandex.ru/pay/page?id=529354
находиться ссылка на модуль JoomShopping Joomla.
но она является 1.5.5 версии.
Я установил ПООЧЕРЕДНО оба модуля на последнюю версию JoomShopping и Joomla.
Оказалось что модуль этой ветки имеет версию 1.0.11 при запуске в Админке не выдает глобальных ошибок. А модуль более новой версии  1.5.5 в Админке выдает кучу ошибок в настройках ее.

Почему модуль этой ветки имеет версию 1.0.11.?
Почему рабочая версия модуля имеет версию меньшую чем не рабочая?
Почему модуль для яндексКасса 2 имеет версию 1 а не 2?
Почему по указанной ссылке скачка модуля не рабочей версии 1.5.5 и тем более что если она более старой версии?
Какая версия является более актуальной(более новой) и будет поддерживаться на следующих версиях CMS и JoomShopping?
Иправьте ссылки на сайте Яндекс.
Исправьте версию модуля 1 на 2, если я правильно понял.

**Comment by ostulov** [comment]
Разные версии модули предназначены для разных схем подключения к Яндекс.Кассе.

Для подключения по схеме - https://github.com/yandex-money/yandex-money-cms-v2-joomshopping (последняя версия 1.0.12).
Для подключения по схеме HTTP - https://github.com/yandex-money/yandex-money-cms-joomla (последняя версия 1.5.5).
Остальной функционал модулей является идентичным. Вы можете использовать любую из версий.

API-схема подключения к Яндекс.Кассе является более новой, она устанавливается автоматически для  подключающихся магазинов. 
Обе ветки модулей поддерживаются, однако последующее добавление новых функций будет происходить только для API-версии модуля.

Если у Вас возникают проблемы с модулем, напишите подробную информацию о возникающей проблеме на почту cms@yamoney.ru

**Comment by korenevskiy** [comment]
Я в первой строчке указал ссылку на яндекс сайт. где выложена ссылка на устаревший модуль.
Замените ссылку там на актуальную API версию.
